apiVersion: tekton.dev/v1beta1
kind: Task

metadata:
  name: crda-report

spec:
  description: >-
    This is the task for scanning dependencies present in the given manifest file using CRDA CLI. 
    It will provide vulnerability details similar to Red Hat Dependency Analytics platform.

    This task accepts following parameters
    - site-pkg:- Target directory for installing dependencies.
    - work-dir:- Project directory having manifest file.
    - manifest:- Name of the manifest file.
    - image:- CRDA image name and tag.

  # Task parameters take values from global parameters  
  params:
    - name: site-pkg
      default: $(params.site-pkg)
    - name: work-dir
      default: $(params.work-dir)
    - name: manifest
      default: $(params.manifest)
    - name: image
      default: $(params.image)

  # Task definition
  steps:
    - name: crda-report
      image: $(params.image)
      command: ['/bin/bash', '-c']
      args:
        - export PYTHONPATH=$(params.site-pkg) && crda analyse --file $(params.work-dir)/$(params.manifest)

  # Task workspace take values from global workspace
  workspaces:
    - name: output